(function0Name)
(defun function1name ( fun1arg ) function1Content )
(defun function2name
  ( fun1arg )
  (function2Content)
  (defun function3name ( fun1arg ) function3Content )
  (defun function3name ( fun1arg ) function3Content )
  (defun function3name ( fun1arg ) function3Content )
)
(DT:James arg1 arg2)
(DT:Bond arg1 arg2)
(defun function4name ( fun1arg ) function4Content )
